language: java
sudo: true
services:
  - docker
branches:
  only:
    - master
script:
  - mvn clean package -Dmaven.test.skip=true
  - docker build -t lmikoto/bot .
  - docker login --username=$DOCKER_USER -p=$DOCKER_PASSWORD
  - docker push lmikoto/bot
before_install:
  - openssl aes-256-cbc -K $encrypted_de6d150a673d_key -iv $encrypted_de6d150a673d_iv -in key.pem.enc -out ~/.ssh/key.pem -d
  - cp ./ssh_config ~/.ssh/config
  - chmod 600 ~/.ssh/key.pem
addons:
  ssh_known_hosts:
    - 47.102.216.171
after_success:
  - ssh miko "cd /root/bot;git pull;docker pull lmikoto/bot;docker-compose down;docker-compose up -d;docker system prune --all --force"
