version: '3'
services:
  bot:
    image: lmikoto/bot:latest
    container_name: bot
    ports:
      - 8080:8080
    networks:
      - net
    external_links:
      - mysqldb
      - kq
    env_file:
      - .env
networks:
  net:
    external: true