version: '3'
services:
  bot:
    image: lmikoto/bot:latest
    container_name: bot
    ports:
      - 8080:8080
    networks:
      - net
    external_links:
      - mysqldb
    environment:
      HOST: 127.0.0.1
networks:
  net:
    external: true