spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:anywhere}
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/bot?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
kq:
  host: ${QQWEBHOST:http://localhost:5700}
xz:
  key: ${XZ_KEY:}
tg:
  token: ${TG_TOKEN:}
  id: ${TG_ID:}
olami:
  key: ${OLAMI_KEY:}
  secret: ${OLAMI_SECRET:}
server:
  port: ${PORT:8080}